export enum MapImage {
    Ahnkahet = "Ahnkahet.jpg",
    AzjolNerubHadronoxsLair = "AzjolNerubHadronoxsLair.jpg",
    AzjolNerubTheGildedGate = "AzjolNerubTheGildedGate.jpg",
    BoreanTundra = "BoreanTundra.jpg",
    CrystalsongForest = "CrystalsongForest.jpg",
    Dalaran = "Dalaran.jpg",
    DalaranSewers = "DalaranSewers.jpg",
    Dragonblight = "Dragonblight.jpg",
    DraktharonKeepTheVestibules = "DraktharonKeepTheVestibules.jpg",
    ElwynnForest = "ElwynnForest.jpg",
    GrizzlyHills = "GrizzlyHills.jpg",
    Gundrak = "Gundrak.jpg",
    HallsOfLightning = "HallsOfLightning.jpg",
    HallsOfStone = "HallsOfStone.jpg",
    HowlingFjord = "HowlingFjord.jpg",
    Icecrown = "Icecrown.jpg",
    IcecrownCitadel = "IcecrownCitadel.jpg",
    Inscription = "Inscription.jpg",
    LakeWintergrasp = "LakeWintergrasp.jpg",
    Naxxramas = "Naxxramas.jpg",
    Northrend = "Northrend.jpg",
    OnyxiasLair = "OnyxiasLair.jpg",
    SholazarBasin = "SholazarBasin.jpg",
    StormPeaks = "StormPeaks.jpg",
    TheArgentColiseum = "TheArgentColiseum.jpg",
    TheNexus = "TheNexus.jpg",
    TheOculusBandOfVariance = "TheOculusBandOfVariance.jpg",
    TheOculusBandOfTransmutation = "TheOculusBandOfTransmutation.jpg",
    TirisfalGlades = "TirisfalGlades.jpg",
    Transmutation = "Transmutation.jpg",
    UlduarBaseCamp = "UlduarBaseCamp.jpg",
    UlduarInnerSanctum = "UlduarInnerSanctum.jpg",
    UlduarPrisonOfYoggSaron = "UlduarPrisonOfYoggSaron.jpg",
    UtgardeKeep = "UtgardeKeep.jpg",
    UtgardePinnacleUpperPinnacle = "UtgardePinnacleUpperPinnacle.jpg",
    ZulDrak = "ZulDrak.jpg",

    // New
    Azeroth = "Azeroth.jpg",
    DarkmoonIsland = "DarkmoonIsland.jpg",
    Deepholm = "Deepholm.jpg",
    Enchanting = "Enchanting.jpg",
    Feralas = "Feralas.jpg",
    LostCityOfTheTolvir = "LostCityOfTheTolvir.jpg",
    MoltenFront = "MoltenFront.jpg",
    MountHyjal = "MountHyjal.jpg",
    Prospecting = "Prospecting.jpg",
    TolBarad = "TolBarad.jpg",
    TolBaradPeninsula = "TolBaradPeninsula.jpg",
    TransmutationWithoutCD = "TransmutationWithoutCD.png",
    TransmutationWithCD = "TransmutationWithCD.png",
    TwilightHighlands = "TwilightHighlands.jpg",
    Uldum = "Uldum.jpg",
    VashjirAbyssalDepths = "VashjirAbyssalDepths.jpg",
    VashjirKelptharForest = "VashjirKelptharForest.jpg",
    VashjirShimmeringExpanse = "VashjirShimmeringExpanse.jpg",
    VortexPinnacle = "VortexPinnacle.jpg",
    ZulGurub = "ZulGurub.jpg",


}