export enum MapImage {
    Azeroth = "Azeroth.jpg",
    DarkmoonIsland = "DarkmoonIsland.jpg",
    Deepholm = "Deepholm.jpg",
    Enchanting = "Enchanting.jpg",
    Feralas = "Feralas.jpg",
    LostCityOfTheTolvir = "LostCityOfTheTolvir.jpg",
    MoltenFront = "MoltenFront.jpg",
    MountHyjal = "MountHyjal.jpg",
    Prospecting = "Prospecting.jpg",
    TolBarad = "TolBarad.jpg",
    TolBaradPeninsula = "TolBaradPeninsula.jpg",
    TransmutationWithoutCD = "TransmutationWithoutCD.png",
    TransmutationWithCD = "TransmutationWithCD.png",
    TwilightHighlands = "TwilightHighlands.jpg",
    Uldum = "Uldum.jpg",
    VashjirAbyssalDepths = "VashjirAbyssalDepths.jpg",
    VashjirKelptharForest = "VashjirKelptharForest.jpg",
    VashjirShimmeringExpanse = "VashjirShimmeringExpanse.jpg",
    VortexPinnacle = "VortexPinnacle.jpg",
    ZulGurub = "ZulGurub.jpg",
}